import { Outfit } from "next/font/google";
import "../../public/css/style.css";
import "../../public/css/plugins/bootstrap-grid.css";
import "../../public/css/plugins/fancybox.min.css";
import "../../public/css/plugins/swiper.min.css";
import "./globals.css";
import Script from "next/script";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Night Owl",
  default: "Night Owl",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>{" "}
      <Script type="text/javascript" src="js/plugins/jquery.min.js" />
      <Script type="text/javascript" src="js/plugins/swup.min.js" async />
      <Script type="text/javascript" src="js/plugins/swiper.min.js" async />
      <Script type="text/javascript" src="js/plugins/fancybox.min.js" async />
      <Script type="text/javascript" src="js/plugins/gsap.min.js" async />
      <Script type="text/javascript" src="js/plugins/smooth-scroll.js" async />
      {/* <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"
        async
      /> */}
      {/* <Script
        src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll@15/dist/smooth-scroll.polyfills.min.js"
        async
      /> */}
      <Script
        type="text/javascript"
        src="js/plugins/ScrollTrigger.min.js"
        async
      />
      <Script type="text/javascript" src="js/plugins/ScrollTo.min.js" async />
      <Script type="text/javascript" src="js/main.js" async />
    </html>
  );
}
export default RootLayout;
