import { Outfit } from "next/font/google";
import "../../public/css/style.css";
import "../../public/css/plugins/bootstrap-grid.css";
import "../../public/css/plugins/fancybox.min.css";
import "../../public/css/plugins/swiper.min.css";
import "./globals.css";
import Script from "next/script";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Night Owl",
  default: "Night Owl",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>{" "}
      <Script src="js/plugins/jquery.min.js" defer />
      <Script src="js/plugins/swup.min.js" defer />
      <Script src="js/plugins/swiper.min.js" defer />
      <Script src="js/plugins/fancybox.min.js" defer />
      <Script src="js/plugins/gsap.min.js" defer />
      {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js" /> */}
      <Script src="js/plugins/smooth-scroll.js" defer />
      <Script src="js/plugins/ScrollTrigger.min.js" defer />
      <Script src="js/plugins/ScrollTo.min.js" defer />
      <Script src="js/main.js" defer />
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"
        async
      />
    </html>
  );
}
export default RootLayout;
